version: '3.8'

services:
  db:
    image: postgres:13.1-alpine
    restart: always
    container_name: bankingapp-db
    environment:
      POSTGRES_DB: bankingapp-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - bankingappNetwork

  bankingapp:
    image: 'bankingapp:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bankingapp
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/bankingapp-db
    depends_on:
      - db
    networks:
      - bankingappNetwork

networks:
  bankingappNetwork:
    driver: bridge

