version: '3.8'

services:
  db:
    image: mysql
    restart: always
    container_name: bankingapp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankingapp-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
